### ISSUE TITLE
JavaScript capstone review 

### ISSUE THREAD

**Issue by Armynerh** [Armynerh/javascript-capstone#21]
Below are the requirements for this issue:
- Project link https://github.com/Armynerh/javascript-capstone
This is the Kanban set-up for the Javascript capstone project. The capstone project is a two-person team with @Armynerh and @Danny-imo

**Comment by taldr27** [comment]
# Status: Approved! 🟢 
Hi @Armynerh, @Danny-imo , 

Your kanban board is complete! :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights
✅ Kanban board working fine.
✅ Good job assigning your cards.

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_
